FROM node:18 AS builder

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build
FROM nginx:alpine
RUN apk add --no-cache gettext
WORKDIR /usr/share/nginx/html
COPY --from=builder /app/build .
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]

