# Nome do workflow (aparece na aba "Actions" do GitHub)
name: CI

# Eventos que vão disparar o workflow
on:
  push:                   # Quando houver um push...
    branches: [ master ]  # ...no branch "master"

  pull_request:           # Ou quando houver um pull request...
    branches: [ master ]  # ...em direção ao branch "master"

# Definição dos jobs (tarefas que serão executadas)
jobs:
  build:                    # Nome do job
    runs-on: ubuntu-latest  # Ambiente onde o job será executado (máquina virtual com Ubuntu)

    steps:                  # Passos que o job vai seguir
      - name: Checkout do código
        uses: actions/checkout@v3  # Faz o download do código do repositório

      - name: Configurar Node.js
        uses: actions/setup-node@v3  # Configura o Node.js no ambiente
        with:
          node-version: '18'        # Define a versão do Node.js que será usada

      - name: Instalar dependências
        run: npm install            # Instala as dependências do projeto com npm

      - name: Rodar testes
        run: npm test               # Roda os testes definidos no projeto
